(function(){
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={summary:null,logins:[],journeys:[],funnels:[],days:28};
const fmtDate=v=>v?new Date(String(v).replace(' ','T')+'Z').toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'}):'–';
const fmtDuration=ms=>{ms=Number(ms||0);if(!ms)return '–';const s=Math.round(ms/1000);return s<60?`${s} s`:`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')} min`;};
const eventLabel=n=>({page_view:'Seitenaufruf',module_view:'Modulaufruf',ui_action:'UI-Aktion',dwell_time:'Verweildauer',recipe_created:'Rezept erstellt',recipe_updated:'Rezept bearbeitet',wallet_saved:'Inspiration gespeichert',wallet_recipe_connected:'Inspiration ↔ Rezept',wallet_food_moment_connected:'Inspiration ↔ Food Moment',food_moment_created:'Food Moment erstellt',food_moment_updated:'Food Moment bearbeitet',food_moment_repeated:'Food Moment neu geplant',planning_slot_saved:'Planung gespeichert',planning_slot_removed:'Planung entfernt',week_template_applied:'Wochenplan angewendet',week_template_created:'Wochenplan erstellt',recipe_to_shopping:'Rezept → Einkauf',food_moment_to_shopping:'Food Moment → Einkauf',shopping_manual_added:'Einkauf manuell ergänzt',shopping_item_toggled:'Einkaufsstatus geändert',shopping_completed_cleared:'Erledigte Einkäufe entfernt',client_error:'Frontend-Fehler',request_error:'Request-Fehler',form_abandoned:'Formular abgebrochen',search_empty:'Leere Suche',search_used:'Suche verwendet',home_intent:'Home-Einstieg'}[n]||n);
const moduleLabel=p=>{const x=String(p||'');return x.includes('foodMomentCreate')?'Food Moment erstellen':x.includes('foodMoments')?'Food Moments':x.includes('mealPlan')?'Planen':x.includes('recipes')?'Rezepte':x.includes('wallet')?'Inspirationen':x.includes('shopping')?'Einkaufen':x.includes('admin')?'Admin':x.includes('index')?'Home':x||'Unbekannt';};
async function api(path){const r=await AuthShell.request(path),text=await r.text();let d=null;try{d=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(r.status===403?'Platform-Admin-Rechte erforderlich.':(d?.error||`HTTP ${r.status}`));return d;}
function trendFromDaily(daily,key){if(!daily?.length)return 0;const mid=Math.floor(daily.length/2),a=daily.slice(0,mid).reduce((s,x)=>s+Number(x[key]||0),0),b=daily.slice(mid).reduce((s,x)=>s+Number(x[key]||0),0);return a?Math.round((b-a)/a*100):b?100:0;}
function kpi(label,value,trend,icon){const positive=trend>=0;return `<article class="analytics-kpi"><div class="analytics-kpi-icon">${icon}</div><div><span>${esc(label)}</span><strong>${esc(value)}</strong><small class="${positive?'is-up':'is-down'}">${positive?'↑':'↓'} ${Math.abs(trend)} % <em>vs. erste Hälfte</em></small></div></article>`;}
function sparkline(values){if(!values.length)return '<div class="analytics-empty">Noch keine Daten</div>';const w=600,h=190,max=Math.max(...values,1),pts=values.map((v,i)=>`${20+i*(w-40)/Math.max(values.length-1,1)},${h-20-(v/max)*(h-45)}`).join(' ');return `<svg class="analytics-line-chart" viewBox="0 0 ${w} ${h}" role="img"><line x1="20" y1="${h-20}" x2="${w-20}" y2="${h-20}"/><polyline points="${pts}"/>${values.map((v,i)=>`<circle cx="${20+i*(w-40)/Math.max(values.length-1,1)}" cy="${h-20-(v/max)*(h-45)}" r="4"><title>${v}</title></circle>`).join('')}</svg>`;}
function miniTable(rows,cols){return `<div class="analytics-mini-table">${rows.map(r=>`<div>${cols.map(c=>`<span>${esc(c(r))}</span>`).join('')}</div>`).join('')}</div>`;}
function render(){const d=state.summary||{},t=d.totals||{},daily=d.daily||[],eventMap=Object.fromEntries((d.events||[]).map(e=>[e.event_name,e.count]));
 const loginTrend=trendFromDates(state.logins,state.days); const moduleViews=(d.modules||[]).reduce((a,x)=>a+Number(x.views||0),0); const links=(eventMap.wallet_recipe_connected||0)+(eventMap.wallet_food_moment_connected||0); const shopping=(eventMap.recipe_to_shopping||0)+(eventMap.food_moment_to_shopping||0)+(eventMap.shopping_manual_added||0);
 $('analytics-kpis').innerHTML=kpi('Aktive User',t.active_users||0,trendFromDaily(daily,'users'),'♙')+kpi('Logins',state.logins.length,loginTrend,'↪')+kpi('Modulaufrufe',moduleViews,trendFromDaily(daily,'events'),'▣')+kpi('Food Moments verknüpft',links,trendFromDaily(daily,'connections'),'♡')+kpi('Einkaufsaktionen',shopping,trendFromDaily(daily,'connections'),'⌑');
 $('analytics-activity-chart').innerHTML=sparkline(daily.map(x=>x.users));
 const maxMod=Math.max(...(d.modules||[]).slice(0,7).map(x=>x.views),1);$('analytics-top-modules').innerHTML=(d.modules||[]).slice(0,7).map(m=>`<div class="analytics-bar-row"><span>${esc(moduleLabel(m.path))}</span><div><i style="width:${Math.round(m.views/maxMod*100)}%"></i></div><strong>${m.views}</strong></div>`).join('')||'<p class="analytics-empty">Noch keine Daten.</p>';
 renderDevices(); renderAnomalies(); renderFunnelPreview(); renderRetention(); renderPreviews(); renderDeepTables();
}
function trendFromDates(rows,days){const now=Date.now(),half=days*86400000/2;let recent=0,old=0;rows.forEach(r=>{const age=now-new Date(String(r.login_at).replace(' ','T')+'Z').getTime();if(age<=half)recent++;else old++;});return old?Math.round((recent-old)/old*100):recent?100:0;}
function renderDevices(){const counts={};state.logins.forEach(x=>counts[x.device]=(counts[x.device]||0)+1);const total=state.logins.length||1,entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);let start=0;const stops=entries.map(([k,v],i)=>{const pct=v/total*100,s=`var(--analytics-accent-${(i%5)+1}) ${start}% ${start+pct}%`;start+=pct;return s;});$('analytics-devices').innerHTML=`<div class="analytics-device-layout"><div class="analytics-donut" style="background:conic-gradient(${stops.join(',')})"><b>${state.logins.length}<small>Logins</small></b></div><div class="analytics-legend">${entries.map(([k,v],i)=>`<div><i class="a${(i%5)+1}"></i><span>${esc(k)}</span><strong>${Math.round(v/total*100)}%</strong></div>`).join('')}</div></div>`;}
function renderAnomalies(){const d=state.summary||{},t=d.totals||{},items=[];(d.friction||[]).forEach(x=>items.push({label:eventLabel(x.event_name),value:`${x.count}×`,score:x.count}));const modules=(d.modules||[]).filter(x=>x.avg_dwell_ms>180000).slice(0,2);modules.forEach(x=>items.push({label:`Lange Verweildauer: ${moduleLabel(x.path)}`,value:fmtDuration(x.avg_dwell_ms),score:x.avg_dwell_ms/1000}));if((d.concept_metrics?.connection_rate||0)<30)items.push({label:'Niedrige Verknüpfungsquote',value:`${d.concept_metrics?.connection_rate||0}%`,score:100});if(!items.length)items.push({label:'Keine auffälligen Friction-Signale',value:'✓',score:0});$('analytics-anomalies').innerHTML=items.sort((a,b)=>b.score-a.score).slice(0,5).map((x,i)=>`<div class="analytics-alert-row"><b>${i+1}</b><span>${esc(x.label)}</span><strong>${esc(x.value)}</strong></div>`).join('');}
function renderFunnelPreview(){const f=state.funnels[0];if(!f){$('analytics-funnel-preview').innerHTML='<p class="analytics-empty">Noch keine Daten.</p>';return;}const base=f.steps[0]?.sessions||0;$('analytics-funnel-preview').innerHTML=`<h3>${esc(f.label)}</h3>`+f.steps.map(s=>{const pct=base?Math.round(s.sessions/base*100):0;return `<div class="analytics-funnel-row"><span>${esc(eventLabel(s.step))}</span><div><i style="width:${pct}%"></i></div><strong>${s.sessions} · ${pct}%</strong></div>`;}).join('');}
function renderRetention(){const r=state.summary?.retention||{};$('analytics-retention').innerHTML=[1,7,14,30].map(day=>{const x=r['d'+day]||{};return `<div class="analytics-retention-row"><span>Tag ${day} (D${day})</span><div><i style="width:${x.rate||0}%"></i></div><strong>${x.rate||0}%</strong></div>`;}).join('');}
function renderPreviews(){const users=state.summary?.users||[];$('analytics-login-preview').innerHTML=miniTable(state.logins.slice(0,5),[x=>fmtDate(x.login_at),x=>x.display_name||x.email,x=>`${x.device}/${x.os}`]);$('analytics-actions-preview').innerHTML=miniTable(state.journeys.slice(0,5),[x=>fmtDate(x.created_at),x=>x.display_name||x.email||'',x=>eventLabel(x.event_name)]);$('analytics-user-preview').innerHTML=miniTable(users.slice(0,5),[x=>x.display_name||x.email,x=>`${x.events} Aktionen`,x=>fmtDate(x.last_seen)]);}
function renderDeepTables(){const d=state.summary||{},loginsByUser={};state.logins.forEach(x=>{const z=loginsByUser[x.user_id]||(loginsByUser[x.user_id]={count:0,days:new Set(),devices:{},last:null});z.count++;z.days.add(String(x.login_at).slice(0,10));z.devices[x.device]=(z.devices[x.device]||0)+1;if(!z.last||x.login_at>z.last)z.last=x.login_at;});
 $('analytics-users-table').innerHTML=(d.users||[]).map(u=>{const l=loginsByUser[u.user_id]||{count:0,days:new Set(),devices:{}};const mix=Object.entries(l.devices).map(([k,v])=>`${k} ${v}`).join(' · ')||'–';return `<tr class="analytics-user-table-row" data-user-id="${u.user_id}"><td><strong>${esc(u.display_name||u.email)}</strong><small>${esc(u.email||'')}</small></td><td>${fmtDate(l.last||u.last_seen)}</td><td>${l.count}</td><td>${u.sessions}</td><td>${l.days.size}</td><td>${u.events}</td><td>${u.connections}</td><td>${esc(mix)}</td></tr>`;}).join('')||emptyRow(8);
 $('analytics-journeys-table').innerHTML=state.journeys.map(e=>`<tr><td>${fmtDate(e.created_at)}</td><td>${esc(e.display_name||e.email||`User ${e.user_id}`)}</td><td>${esc((e.session_id||'–').slice(0,10))}</td><td>${esc(eventLabel(e.event_name))}</td><td>${esc(moduleLabel(e.path))}</td><td>${esc(e.properties?.label||e.entity_type||'–')}</td></tr>`).join('')||emptyRow(6);
 $('analytics-modules-table').innerHTML=(d.modules||[]).map(m=>`<tr><td><strong>${esc(moduleLabel(m.path))}</strong><small>${esc(m.path)}</small></td><td>${m.views}</td><td>${m.users}</td><td>${fmtDuration(m.avg_dwell_ms)}</td><td>${m.users?(m.views/m.users).toFixed(1):'0'}</td></tr>`).join('')||emptyRow(5);
 $('analytics-events-table').innerHTML=(d.events||[]).map(e=>`<tr><td>${esc(eventLabel(e.event_name))}<small>${esc(e.event_name)}</small></td><td>${esc(e.event_category)}</td><td>${e.count}</td><td>${e.users}</td><td>${e.users?(e.count/e.users).toFixed(1):'0'}</td></tr>`).join('')||emptyRow(5);
 $('analytics-funnels').innerHTML=state.funnels.map(f=>{const base=f.steps[0]?.sessions||0;return `<article class="analytics-panel"><h3>${esc(f.label)}</h3>${f.steps.map((s,i)=>{const pct=base?Math.round(s.sessions/base*100):0;return `<div class="analytics-funnel-row"><span>${i+1}. ${esc(eventLabel(s.step))}</span><div><i style="width:${pct}%"></i></div><strong>${s.sessions} · ${pct}%</strong></div>`;}).join('')}</article>`;}).join('')||'<p class="analytics-empty">Noch keine Funnel-Daten.</p>';
 $('analytics-friction-table').innerHTML=(d.friction||[]).map(e=>`<tr><td>${esc(eventLabel(e.event_name))}<small>${esc(e.event_name)}</small></td><td>${e.count}</td><td>${e.users}</td><td>${tPct(e.count,d.totals?.total_events)}%</td></tr>`).join('')||emptyRow(4);
 document.querySelectorAll('[data-user-id]').forEach(el=>el.onclick=()=>showUser(el.dataset.userId)); filterUsers();}
function tPct(a,b){return b?((a/b)*100).toFixed(1):'0.0';}function emptyRow(n){return `<tr><td colspan="${n}" class="analytics-empty">Noch keine Daten im gewählten Zeitraum.</td></tr>`;}
async function showUser(id){try{const d=await api(`/analytics/users/${id}?days=${state.days}`);$('analytics-user-detail').innerHTML=`<div class="analytics-user-detail-head"><div><p class="recipe-kicker">User Journey</p><h3>${esc(d.user.display_name||d.user.email)}</h3><span>${esc(d.user.email||'')}</span></div><button type="button" id="analytics-detail-close">×</button></div><div class="analytics-user-detail-stats"><span><b>${d.sessions.length}</b> Sessions</span><span><b>${d.events.length}</b> Events</span><span><b>${d.events[0]?fmtDate(d.events[0].created_at):'–'}</b> letzte Aktivität</span></div><div class="analytics-timeline-detail">${d.events.slice(0,150).map(e=>`<div><time>${fmtDate(e.created_at)}</time><strong>${esc(eventLabel(e.event_name))}</strong><span>${esc(moduleLabel(e.path))}${e.properties?.label?` · ${esc(e.properties.label)}`:''}</span></div>`).join('')}</div>`;$('analytics-detail-close').onclick=()=>$('analytics-user-detail').innerHTML='';}catch(e){showError(e.message);}}
function filterUsers(){const q=($('analytics-user-search')?.value||'').toLowerCase();document.querySelectorAll('.analytics-user-table-row').forEach(r=>r.hidden=q&&!r.textContent.toLowerCase().includes(q));}
function csvEscape(v){return `"${String(v??'').replace(/"/g,'""')}"`;}function downloadCsv(name,headers,rows){const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvEscape).join(';')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`FoodMoment_${name}_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function exportData(type){const d=state.summary||{};if(type==='users')downloadCsv('User_Logins',['User','E-Mail','Events','Sessions','Connections','Erste Aktivität','Letzte Aktivität'],(d.users||[]).map(u=>[u.display_name,u.email,u.events,u.sessions,u.connections,u.first_seen,u.last_seen]));if(type==='journeys')downloadCsv('Klickstrecken',['Zeitpunkt','User','E-Mail','Session','Event','Kategorie','Pfad','Detail'],state.journeys.map(e=>[e.created_at,e.display_name,e.email,e.session_id,eventLabel(e.event_name),e.event_category,e.path,e.properties?.label||e.entity_type||'']));if(type==='modules')downloadCsv('Module',['Modul','Pfad','Aufrufe','User','Ø Verweildauer ms'],(d.modules||[]).map(m=>[moduleLabel(m.path),m.path,m.views,m.users,m.avg_dwell_ms]));if(type==='events')downloadCsv('Funktionen',['Event','Bezeichnung','Kategorie','Anzahl','User'],(d.events||[]).map(e=>[e.event_name,eventLabel(e.event_name),e.event_category,e.count,e.users]));if(type==='friction')downloadCsv('Friction',['Event','Bezeichnung','Anzahl','User','Anteil %'],(d.friction||[]).map(e=>[e.event_name,eventLabel(e.event_name),e.count,e.users,tPct(e.count,d.totals?.total_events)]));if(type==='funnels')downloadCsv('Funnels',['Funnel','Schritt','Sessions','Conversion %'],state.funnels.flatMap(f=>{const b=f.steps[0]?.sessions||0;return f.steps.map(s=>[f.label,eventLabel(s.step),s.sessions,b?Math.round(s.sessions/b*100):0]);}));}
async function load(){state.days=Number($('analytics-range').value||28);document.body.classList.add('analytics-loading');try{const[d,l,j,f]=await Promise.all([api(`/analytics/summary?days=${state.days}`),api(`/analytics/logins?days=${state.days}`),api(`/analytics/journeys?days=${state.days}&limit=300`),api(`/analytics/funnels?days=${state.days}`)]);state.summary=d;state.logins=l.logins||[];state.journeys=j.events||[];state.funnels=f.funnels||[];render();}catch(e){showError(e.message);}finally{document.body.classList.remove('analytics-loading');}}
function showError(msg){$('analytics-kpis').innerHTML=`<div class="analytics-error">${esc(msg||'Auswertung konnte nicht geladen werden.')}</div>`;}
document.addEventListener('auth:ready',load);$('analytics-refresh')?.addEventListener('click',load);$('analytics-range')?.addEventListener('change',load);$('analytics-user-search')?.addEventListener('input',filterUsers);document.querySelectorAll('.analytics-export').forEach(b=>b.addEventListener('click',()=>exportData(b.dataset.export)));
})();
