const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
let currentMoment=null;let availableWorkspaces=[];
async function api(path,options={}){const h=new Headers(options.headers||{});if(options.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await AuthShell.request(path,{...options,headers:h});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||'Aktion fehlgeschlagen.');return p;}
async function loadMoment(){const id=new URLSearchParams(location.search).get('id');if(!id){$('moment-detail').innerHTML='<p>Food Moment fehlt.</p>';return;}try{currentMoment=await api(`/food-moments/${encodeURIComponent(id)}`);render(currentMoment);}catch(e){$('moment-detail').innerHTML=`<div class="moment-detail-error"><h1>Nicht gefunden.</h1><p>${esc(e.message)}</p></div>`;}}
function when(m){const labels={now:'Jetzt',later_today:'Später heute',tomorrow:'Morgen',weekend:'Am Wochenende',open:'Noch offen'};if(m.moment_date){const d=new Date(m.moment_date+'T12:00:00');return `${d.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long'})}${m.moment_time?` · ${m.moment_time} Uhr`:''}`;}return labels[m.timing_code]||'Noch offen';}
function audience(m){const l={solo:'Nur ich',two:'Zu zweit',family:'Familie',friends:'Freunde',guests:'Gäste',open:'Noch offen'};return `${l[m.audience_code]||'Noch offen'}${m.people_count?` · ${m.people_count} Personen`:''}`;}
function icon(path){return `<svg class="fc-icon" viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`;}
function render(m){const recipe=m.recipes?.[0], inspiration=m.inspirations?.[0];$('moment-detail').innerHTML=`<header class="moment-detail-hero"><div class="moment-detail-hero-row"><div><a href="/foodMoments.html" class="moment-back-link">← Alle Food Moments</a><p class="home-section-kicker">Food Moment</p><h1>${esc(m.title)}</h1></div><div class="moment-detail-actions"><button class="moment-edit-button" type="button" onclick="openMomentEdit()">${icon('<path d="M4 20h4l11-11-4-4L4 16v4z"/><path d="m13 7 4 4"/>')}<span>Bearbeiten</span></button><details class="moment-more"><summary aria-label="Weitere Aktionen">${icon('<circle cx="5" cy="12" r="1.3"/><circle cx="12" cy="12" r="1.3"/><circle cx="19" cy="12" r="1.3"/>')}</summary><div><button type="button" onclick="openMomentEdit(true)">Workspace ändern</button><button type="button" class="is-danger" onclick="deleteMoment()">Food Moment löschen</button></div></details></div></div><div class="moment-detail-meta"><span>${esc(when(m))}</span><span>${esc(audience(m))}</span>${m.workspace?.name?`<span>${esc(m.workspace.name)}</span>`:''}</div></header><section class="moment-detail-grid"><article class="moment-main-card"><p class="home-section-kicker">Was es wird</p>${recipe?`<h2>${esc(recipe.name)}</h2><p>${recipe.portions?`${esc(recipe.portions)} Portionen`:''}${recipe.calories?` · ${esc(recipe.calories)} kcal`:''}</p><a href="/recipeInstructions.html?id=${encodeURIComponent(recipe.id)}">Rezept öffnen →</a>`:`<h2>Noch offen.</h2><p>Dieser Moment darf noch wachsen. Du kannst später ein Rezept oder eine Inspiration ergänzen.</p>`}</article><div class="moment-side-stack"><article class="moment-side-card"><p class="home-section-kicker">Inspiration</p>${inspiration?`<h3>${esc(inspiration.title||'Inspiration')}</h3><p>${esc(inspiration.category||'Aus deiner Wallet')}</p>${inspiration.source_url?`<a href="${esc(inspiration.source_url)}" target="_blank" rel="noopener">Quelle öffnen →</a>`:''}`:'<p>Noch keine Inspiration verknüpft.</p>'}</article><article class="moment-side-card"><p class="home-section-kicker">Vorbereiten</p><h3>Noch ganz entspannt.</h3><p>Einkauf und Inventar-Verknüpfung kommen als nächster Ausbau dazu.</p></article>${m.notes?`<article class="moment-side-card"><p class="home-section-kicker">Notiz</p><p>${esc(m.notes)}</p></article>`:''}</div></section>`;}
function timingForForm(m){return m.moment_date?'date':(m.timing_code||'open');}
async function ensureWorkspaces(){if(availableWorkspaces.length)return availableWorkspaces;const data=await api('/workspaces');availableWorkspaces=Array.isArray(data?.workspaces)?data.workspaces:[];return availableWorkspaces;}
async function openMomentEdit(focusWorkspace=false){if(!currentMoment)return;try{const workspaces=await ensureWorkspaces();const dialog=$('moment-edit-dialog');$('edit-moment-title').value=currentMoment.title||'';$('edit-moment-timing').value=timingForForm(currentMoment);$('edit-moment-date').value=currentMoment.moment_date||'';$('edit-moment-time').value=currentMoment.moment_time||'';$('edit-moment-audience').value=currentMoment.audience_code||'open';$('edit-moment-people').value=currentMoment.people_count||'';$('edit-moment-notes').value=currentMoment.notes||'';const select=$('edit-moment-workspace');select.innerHTML=workspaces.map(w=>`<option value="${esc(w.public_id)}" ${w.public_id===currentMoment.workspace?.public_id?'selected':''}>${esc(w.name)}</option>`).join('');toggleEditDate();$('moment-edit-feedback').textContent='';if(typeof dialog.showModal==='function')dialog.showModal();if(focusWorkspace)setTimeout(()=>select.focus(),60);}catch(e){alert(e.message);}}
function closeMomentEdit(){$('moment-edit-dialog')?.close();}
function toggleEditDate(){$('edit-moment-date-fields')?.classList.toggle('is-hidden',$('edit-moment-timing')?.value!=='date');}
async function saveMomentEdit(e){e.preventDefault();const button=$('moment-edit-save');button.disabled=true;$('moment-edit-feedback').textContent='';try{const timing=$('edit-moment-timing').value;const updated=await api(`/food-moments/${encodeURIComponent(currentMoment.public_id)}`,{method:'PATCH',body:JSON.stringify({title:$('edit-moment-title').value,timing_code:timing,moment_date:timing==='date'?($('edit-moment-date').value||null):null,moment_time:timing==='date'?($('edit-moment-time').value||null):null,audience_code:$('edit-moment-audience').value,people_count:$('edit-moment-people').value||null,notes:$('edit-moment-notes').value,workspace_public_id:$('edit-moment-workspace').value})});const oldWorkspace=currentMoment.workspace?.public_id;currentMoment=updated;closeMomentEdit();if(updated.workspace?.public_id&&updated.workspace.public_id!==oldWorkspace){await AuthShell.switchWorkspace(updated.workspace.public_id);location.href=`/foodMoment.html?id=${encodeURIComponent(updated.public_id)}`;return;}render(updated);}catch(err){$('moment-edit-feedback').textContent=err.message;}finally{button.disabled=false;}}
async function deleteMoment(){if(!currentMoment||!confirm(`„${currentMoment.title}“ wirklich löschen?`))return;try{await api(`/food-moments/${encodeURIComponent(currentMoment.public_id)}`,{method:'DELETE'});location.href='/foodMoments.html';}catch(e){alert(e.message);}}
document.addEventListener('change',e=>{if(e.target?.id==='edit-moment-timing')toggleEditDate();});$('moment-edit-form')?.addEventListener('submit',saveMomentEdit);$('moment-edit-close')?.addEventListener('click',closeMomentEdit);$('moment-edit-cancel')?.addEventListener('click',closeMomentEdit);document.addEventListener('auth:ready',loadMoment);if(window.AuthShell?.isReady?.())loadMoment();
