const momentState={timing:'open',audience:'open',contentType:'recipe',recipeIds:new Set(),walletIds:new Set(),recipes:[],walletItems:[],editId:null,current:null};
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function api(path,options={}){const h=new Headers(options.headers||{});if(options.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await AuthShell.request(path,{...options,headers:h});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||'Aktion fehlgeschlagen.');return p;}
function setChoice(group,value){document.querySelectorAll(`#${group} button`).forEach(b=>b.classList.toggle('is-selected',b.dataset.value===value));}
function timingLabel(){return {now:'Jetzt',later_today:'Später heute',tomorrow:'Morgen',weekend:'Am Wochenende',date:$('moment-date').value?new Date($('moment-date').value+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}):'Bestimmter Tag',open:'Noch offen'}[momentState.timing]||'Noch offen';}
function audienceLabel(){return {solo:'Nur ich',two:'Zu zweit',family:'Familie',friends:'Freunde',guests:'Gäste',open:'Noch offen'}[momentState.audience]||'Noch offen';}
function selectedItems(){const recipes=momentState.recipes.filter(i=>momentState.recipeIds.has(Number(i.id)));const wallets=momentState.walletItems.filter(i=>momentState.walletIds.has(i.public_id));return [...recipes.map(i=>i.name),...wallets.map(i=>i.title)];}
function contentLabel(){const names=selectedItems();if(!names.length)return 'Noch offen';if(names.length===1)return names[0];return `${names.length} Elemente ausgewählt`;}
function suggestedTitle(){const when=timingLabel(),audience=audienceLabel();if(momentState.timing==='open'&&momentState.audience==='open')return '';if(momentState.audience==='open')return when;if(momentState.timing==='open')return audience;return `${when} · ${audience}`;}
function updatePreview(){const auto=suggestedTitle();if(!$('moment-title').dataset.edited&&auto&&!momentState.editId)$('moment-title').value=auto;$('preview-title').textContent=$('moment-title').value.trim()||'Noch ganz offen.';$('preview-when').textContent=timingLabel();$('preview-audience').textContent=audienceLabel();$('preview-content').textContent=contentLabel();}
function renderSelectedSummary(){let el=$('moment-selected-content');if(!el){el=document.createElement('div');el.id='moment-selected-content';el.className='moment-selected-content';$('moment-content-picker').before(el);}const items=[];momentState.recipes.filter(i=>momentState.recipeIds.has(Number(i.id))).forEach(i=>items.push(`<span>Rezept · ${esc(i.name)} <button type="button" data-kind="recipe" data-id="${i.id}" aria-label="Entfernen">×</button></span>`));momentState.walletItems.filter(i=>momentState.walletIds.has(i.public_id)).forEach(i=>items.push(`<span>Inspiration · ${esc(i.title)} <button type="button" data-kind="wallet" data-id="${esc(i.public_id)}" aria-label="Entfernen">×</button></span>`));el.innerHTML=items.length?items.join(''):'<small>Noch nichts ausgewählt.</small>';el.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.kind==='recipe')momentState.recipeIds.delete(Number(b.dataset.id));else momentState.walletIds.delete(b.dataset.id);renderResults();renderSelectedSummary();updatePreview();});}
function renderResults(){const q=$('moment-content-search').value.trim().toLocaleLowerCase('de');const box=$('moment-content-results');if(momentState.contentType==='open'){box.innerHTML='<div class="moment-open-state"><strong>Noch nichts festlegen.</strong><p>Wenn du diese Option wählst, werden bereits ausgewählte Inhalte entfernt.</p><button type="button" id="clear-moment-content" class="secondary-button">Auswahl leeren</button></div>';$('clear-moment-content').onclick=()=>{momentState.recipeIds.clear();momentState.walletIds.clear();renderSelectedSummary();updatePreview();};return;}const isRecipe=momentState.contentType==='recipe';const items=isRecipe?momentState.recipes:momentState.walletItems;const filtered=items.filter(i=>String(i.name||i.title||'').toLocaleLowerCase('de').includes(q));if(!filtered.length){box.innerHTML='<p class="moment-picker-empty">Nichts gefunden.</p>';return;}box.innerHTML=filtered.map(i=>{const id=isRecipe?Number(i.id):i.public_id;const selected=isRecipe?momentState.recipeIds.has(id):momentState.walletIds.has(id);return `<button type="button" class="moment-picker-item ${selected?'is-selected':''}" data-id="${esc(id)}"><span><strong>${esc(i.name||i.title||'Ohne Titel')}</strong><small>${esc(isRecipe?(i.portions?`${i.portions} Portionen`:'Rezept'):(i.category||i.source_platform||'Inspiration'))}</small></span><span>${selected?'✓':'+'}</span></button>`}).join('');box.querySelectorAll('.moment-picker-item').forEach(b=>b.onclick=()=>toggleContent(b.dataset.id));}
function toggleContent(id){if(momentState.contentType==='recipe'){const n=Number(id);momentState.recipeIds.has(n)?momentState.recipeIds.delete(n):momentState.recipeIds.add(n);}else{momentState.walletIds.has(id)?momentState.walletIds.delete(id):momentState.walletIds.add(id);}renderResults();renderSelectedSummary();updatePreview();}
function applyEditMoment(m){momentState.current=m;momentState.timing=m.timing_code||'open';momentState.audience=m.audience_code||'open';momentState.recipeIds=new Set((m.recipes||[]).map(r=>Number(r.id)));momentState.walletIds=new Set((m.inspirations||[]).map(w=>w.public_id));setChoice('timing-choices',momentState.timing);setChoice('audience-choices',momentState.audience);$('moment-date-fields').classList.toggle('is-hidden',momentState.timing!=='date');$('moment-date').value=m.moment_date||'';$('moment-time').value=m.moment_time||'';$('people-count').value=m.people_count||'';$('moment-title').value=m.title||'';$('moment-title').dataset.edited='1';$('moment-notes').value=m.notes||'';document.querySelector('.food-moment-builder-kicker').textContent='Food Moment bearbeiten';document.querySelector('.food-moment-builder h1').textContent='Dein Food Moment.';document.querySelector('.food-moment-builder-intro').textContent='Passe deinen Moment mit derselben vertrauten Maske an.';$('create-food-moment-button').textContent='Änderungen speichern';document.title='Food Moment bearbeiten · Food Moment';}
async function loadSources(){try{const params=new URLSearchParams(location.search);momentState.editId=params.get('edit');const calls=[api('/recipes'),api('/wallet?status=saved')];if(momentState.editId)calls.push(api(`/food-moments/${encodeURIComponent(momentState.editId)}`));const [recipes,wallet,current]=await Promise.all(calls);momentState.recipes=Array.isArray(recipes)?recipes:[];momentState.walletItems=Array.isArray(wallet)?wallet:[];if(current)applyEditMoment(current);const rid=Number(params.get('recipe_id'));if(rid&&!momentState.editId&&momentState.recipes.some(r=>Number(r.id)===rid)){momentState.contentType='recipe';momentState.recipeIds.add(rid);document.querySelectorAll('.moment-content-tabs button').forEach(b=>b.classList.toggle('is-active',b.dataset.content==='recipe'));}
const wid=params.get('wallet_id');if(wid&&!momentState.editId){momentState.contentType='wallet';momentState.walletIds.add(wid);const walletIntent=params.get('wallet_intent');if(walletIntent&&!$('moment-title').dataset.edited){$('moment-title').value=walletIntent;$('moment-title').dataset.edited='1';}document.querySelectorAll('.moment-content-tabs button').forEach(b=>b.classList.toggle('is-active',b.dataset.content==='wallet'));}renderSelectedSummary();renderResults();updatePreview();}catch(e){$('moment-form-feedback').textContent=e.message;}}
document.querySelectorAll('#timing-choices button').forEach(b=>b.onclick=()=>{momentState.timing=b.dataset.value;setChoice('timing-choices',momentState.timing);$('moment-date-fields').classList.toggle('is-hidden',momentState.timing!=='date');updatePreview();});
document.querySelectorAll('#audience-choices button').forEach(b=>b.onclick=()=>{momentState.audience=b.dataset.value;setChoice('audience-choices',momentState.audience);if(momentState.audience==='solo')$('people-count').value=1;if(momentState.audience==='two')$('people-count').value=2;updatePreview();});
document.querySelectorAll('.moment-content-tabs button').forEach(b=>b.onclick=()=>{momentState.contentType=b.dataset.content;document.querySelectorAll('.moment-content-tabs button').forEach(x=>x.classList.toggle('is-active',x===b));$('moment-content-picker').classList.toggle('is-open-choice',momentState.contentType==='open');renderResults();updatePreview();});
$('cancel-food-moment-button')?.addEventListener('click',()=>{if(momentState.editId)location.href=`/foodMoment.html?id=${encodeURIComponent(momentState.editId)}`;else if(history.length>1)history.back();else location.href='/foodMoments.html';});
$('moment-content-search').addEventListener('input',renderResults);$('moment-date').addEventListener('change',updatePreview);$('moment-time').addEventListener('change',updatePreview);$('moment-title').addEventListener('input',()=>{$('moment-title').dataset.edited='1';updatePreview();});
$('food-moment-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('create-food-moment-button');$('moment-form-feedback').textContent='';btn.disabled=true;try{const body={title:$('moment-title').value,timing_code:momentState.timing,moment_date:momentState.timing==='date'?($('moment-date').value||null):null,moment_time:momentState.timing==='date'?($('moment-time').value||null):null,audience_code:momentState.audience,people_count:$('people-count').value||null,recipe_ids:[...momentState.recipeIds],wallet_public_ids:[...momentState.walletIds],notes:$('moment-notes').value};if(!momentState.editId){const params=new URLSearchParams(location.search);if(params.get('recipe_id')){body.source_code='recipe';body.source_reference=String(params.get('recipe_id'));}else if(params.get('wallet_id')){body.source_code='wallet';body.source_reference=params.get('wallet_id');}}const path=momentState.editId?`/food-moments/${encodeURIComponent(momentState.editId)}`:'/food-moments';const saved=await api(path,{method:momentState.editId?'PATCH':'POST',body:JSON.stringify(body)});location.href=`/foodMoment.html?id=${encodeURIComponent(saved.public_id)}`;}catch(err){$('moment-form-feedback').textContent=err.message;}finally{btn.disabled=false;}});
document.addEventListener('auth:ready',loadSources);if(window.AuthShell?.isReady?.())loadSources();
