const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let currentMoment=null,workspaceOptions=[],saveTimer=null,editMode=null,sourceRecipes=[],sourceWallet=[],sourceMoments=[];

async function api(path,options={}){const h=new Headers(options.headers||{});if(options.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await AuthShell.request(path,{...options,headers:h});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||'Aktion fehlgeschlagen.');return p;}
function icon(path){return `<svg class="fc-icon" viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`;}
function when(m){const date=m.moment_date||m.starts_at?.slice(0,10)||'';const time=m.moment_time||(!m.is_all_day&&m.starts_at?m.starts_at.slice(11,16):'');if(date){const d=new Date(date+'T12:00:00');return d.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})+(time?` · ${time}`:'');}const labels={now:'Jetzt',later_today:'Später heute',tomorrow:'Morgen',weekend:'Am Wochenende',open:'Noch offen'};return labels[m.timing_code]||'Noch offen';}
function audience(m){return {solo:'Nur ich',two:'Zu zweit',family:'Familie',friends:'Freunde',guests:'Gäste',open:'Noch offen'}[m.audience_code]||'Noch offen';}
function cardMenu(mode,label='Bearbeiten'){return `<button class="moment-card-menu" type="button" data-moment-edit="${esc(mode)}" aria-label="${esc(label)}" title="${esc(label)}">${icon('<circle cx="5" cy="12" r="1.3"/><circle cx="12" cy="12" r="1.3"/><circle cx="19" cy="12" r="1.3"/>')}</button>`;}
function inspirationImage(i){return i.source_image_url?`<div class="moment-inspiration-image"><img src="${esc(i.source_image_url)}" alt="" loading="lazy" referrerpolicy="no-referrer"></div>`:'';}
function recipeItems(recipes){return recipes.map(r=>`<div class="moment-linked-item"><div><h3>${esc(r.name)}</h3><p>${r.portions?`${esc(r.portions)} Portionen`:''}${r.calories?` · ${esc(r.calories)} kcal`:''}</p></div><a href="/recipeInstructions.html?id=${encodeURIComponent(r.id)}">Öffnen →</a></div>`).join('');}
function inspirationItems(items){return items.map(i=>`<div class="moment-inspiration-item">${inspirationImage(i)}<div class="moment-inspiration-copy"><h3>${esc(i.title||'Inspiration')}</h3><p>${esc(i.category||'Aus deiner Wallet')}</p>${i.source_url?`<a href="${esc(i.source_url)}" target="_blank" rel="noopener">Quelle öffnen →</a>`:''}</div></div>`).join('');}
function childMomentItems(items){return items.map(i=>`<div class="moment-linked-item"><div><h3>${esc(i.title||'Food Moment')}</h3><p>${esc(when(i))}</p></div><a href="/foodMoment.html?id=${encodeURIComponent(i.public_id)}">Öffnen →</a></div>`).join('');}
function missingBubbles(m){const items=[];if(!(m.moment_date||m.starts_at)&&(!m.timing_code||m.timing_code==='open'))items.push(['timing','Wann hinzufügen']);if(!m.audience_code||m.audience_code==='open')items.push(['audience','Für wen hinzufügen']);if(!(m.recipes||[]).length)items.push(['recipes','Rezept hinzufügen']);if(!(m.inspirations||[]).length)items.push(['inspirations','Inspiration hinzufügen']);if(!(m.child_food_moments||[]).length)items.push(['moments','Food Moment hinzufügen']);if(!String(m.notes||'').trim())items.push(['notes','Notiz hinzufügen']);return items.map(([mode,label])=>`<button type="button" class="moment-add-bubble" data-moment-edit="${mode}"><span>＋</span>${esc(label)}</button>`).join('');}

async function loadMoment(){const id=new URLSearchParams(location.search).get('id');if(!id){$('moment-detail').innerHTML='<p>Food Moment fehlt.</p>';return;}try{currentMoment=await api(`/food-moments/${encodeURIComponent(id)}`);render(currentMoment);}catch(e){$('moment-detail').innerHTML=`<div class="moment-detail-error"><h1>Nicht gefunden.</h1><p>${esc(e.message)}</p></div>`;}}
function render(m){const recipes=m.recipes||[],ins=m.inspirations||[];const cards=[];
 if((m.moment_date||m.starts_at)||(m.timing_code&&m.timing_code!=='open'))cards.push(`<article class="moment-content-card moment-card-compact"><div class="moment-card-head"><p class="home-section-kicker">Wann</p>${cardMenu('timing','Zeitpunkt bearbeiten')}</div><h2>${esc(when(m))}</h2></article>`);
 if(m.audience_code&&m.audience_code!=='open')cards.push(`<article class="moment-content-card moment-card-compact"><div class="moment-card-head"><p class="home-section-kicker">Für wen</p>${cardMenu('audience','Personen bearbeiten')}</div><h2>${esc(audience(m))}</h2>${m.people_count?`<p>${esc(m.people_count)} ${Number(m.people_count)===1?'Person':'Personen'}</p>`:''}</article>`);
 if(recipes.length)cards.push(`<article class="moment-content-card moment-card-wide"><div class="moment-card-head"><p class="home-section-kicker">Rezepte</p>${cardMenu('recipes','Rezepte bearbeiten')}</div><div class="moment-linked-list">${recipeItems(recipes)}</div></article>`);
 if(ins.length)cards.push(`<article class="moment-content-card ${ins.length>1?'moment-card-wide':''}"><div class="moment-card-head"><p class="home-section-kicker">Inspiration</p>${cardMenu('inspirations','Inspirationen bearbeiten')}</div><div class="moment-inspiration-list">${inspirationItems(ins)}</div></article>`);
 if((m.child_food_moments||[]).length)cards.push(`<article class="moment-content-card moment-card-wide"><div class="moment-card-head"><p class="home-section-kicker">Bestandteile</p>${cardMenu('moments','Food Moments bearbeiten')}</div><div class="moment-linked-list">${childMomentItems(m.child_food_moments)}</div></article>`);
 if(String(m.notes||'').trim())cards.push(`<article class="moment-content-card"><div class="moment-card-head"><p class="home-section-kicker">Notiz</p>${cardMenu('notes','Notiz bearbeiten')}</div><p class="moment-card-note">${esc(m.notes)}</p></article>`);
 $('moment-detail').innerHTML=`<header class="moment-detail-hero"><div class="moment-detail-hero-row"><div><a href="/foodMoments.html" class="moment-back-link">← Alle Food Moments</a><p class="recipe-kicker">Food Moment</p><h1>${esc(m.title)}</h1></div><div class="moment-detail-actions">${recipes.length?`<button class="secondary-action-button moment-shopping-button" type="button" onclick="addMomentToShoppingList()">${icon('<path d="M4 5h2l2 10h9l2-7H7"/><circle cx="10" cy="19" r="1"/><circle cx="17" cy="19" r="1"/>')}<span>Zum Einkauf</span></button>`:''}<button class="moment-edit-button" type="button" onclick="location.href='/foodMomentCreate.html?edit=${encodeURIComponent(m.public_id)}'">${icon('<path d="M4 20h4l11-11-4-4L4 16v4z"/><path d="m13 7 4 4"/>')}<span>Alles bearbeiten</span></button><details class="moment-more"><summary aria-label="Weitere Aktionen">${icon('<circle cx="5" cy="12" r="1.3"/><circle cx="12" cy="12" r="1.3"/><circle cx="19" cy="12" r="1.3"/>')}</summary><div><button type="button" onclick="openMomentWorkspaces()">Workspaces zuordnen</button><button type="button" class="is-danger" onclick="deleteMoment()">Food Moment löschen</button></div></details></div></div><div class="moment-detail-meta">${(m.workspace_assignments||[]).map(w=>`<span>${esc(w.name)}</span>`).join('')}</div></header><div class="moment-add-bubbles" aria-label="Noch offene Angaben">${missingBubbles(m)}</div><section class="moment-dynamic-grid">${cards.join('')||'<div class="moments-empty"><h2>Noch ganz offen.</h2><p>Füge oben die ersten Bausteine zu deinem Food Moment hinzu.</p></div>'}</section>`;
 document.querySelectorAll('[data-moment-edit]').forEach(b=>b.addEventListener('click',()=>openSectionEditor(b.dataset.momentEdit)));
}

async function ensureSources(){if(sourceRecipes.length||sourceWallet.length||sourceMoments.length)return;const [recipes,wallet,moments]=await Promise.all([api('/recipes'),api('/wallet?status=saved'),api('/food-moments')]);sourceRecipes=Array.isArray(recipes)?recipes:[];sourceWallet=Array.isArray(wallet)?wallet:[];sourceMoments=(Array.isArray(moments)?moments:[]).filter(m=>m.public_id!==currentMoment?.public_id&&!m.is_component);}
function editorTitle(mode){return {timing:'Wann findet der Moment statt?',audience:'Für wen ist der Moment?',recipes:'Rezepte auswählen',inspirations:'Inspirationen auswählen',moments:'Food Moments als Bestandteile',notes:'Notiz bearbeiten'}[mode]||'Food Moment bearbeiten';}
function editorMarkup(mode){
 if(mode==='timing'){const timingUi=(currentMoment.moment_date||currentMoment.starts_at)?'date':(currentMoment.timing_code||'open');return `<div class="moment-section-editor-options" data-choice="timing">${[['now','Jetzt'],['later_today','Später heute'],['tomorrow','Morgen'],['weekend','Am Wochenende'],['date','Bestimmter Tag'],['open','Noch offen']].map(([v,l])=>`<button type="button" data-value="${v}" class="${timingUi===v?'is-selected':''}">${l}</button>`).join('')}</div><div id="moment-section-date" class="moment-section-date ${timingUi==='date'?'':'is-hidden'}"><input type="date" id="moment-edit-date" value="${esc(currentMoment.moment_date||currentMoment.starts_at?.slice(0,10)||'')}"><input type="time" id="moment-edit-time" value="${esc(currentMoment.moment_time||(!currentMoment.is_all_day&&currentMoment.starts_at?currentMoment.starts_at.slice(11,16):''))}"></div>`;}
 if(mode==='audience')return `<div class="moment-section-editor-options" data-choice="audience">${[['solo','Nur ich'],['two','Zu zweit'],['family','Familie'],['friends','Freunde'],['guests','Gäste'],['open','Noch offen']].map(([v,l])=>`<button type="button" data-value="${v}" class="${currentMoment.audience_code===v?'is-selected':''}">${l}</button>`).join('')}</div><label class="moment-edit-people">Personen <input type="number" min="1" id="moment-edit-people" value="${esc(currentMoment.people_count||'')}"></label>`;
 if(mode==='notes')return `<textarea id="moment-edit-notes" rows="6" placeholder="Was möchtest du für diesen Moment festhalten?">${esc(currentMoment.notes||'')}</textarea>`;
 if(mode==='moments'){const selected=new Set((currentMoment.child_food_moments||[]).map(x=>String(x.public_id)));return `<div class="moment-section-search"><input id="moment-section-search" type="search" placeholder="Food Moments durchsuchen …"></div><div id="moment-section-picker" class="moment-section-picker">${sourceMoments.map(i=>`<label class="moment-section-picker-item"><span><span><strong>${esc(i.title||'Food Moment')}</strong><small>${esc(when(i))}</small></span></span><input type="checkbox" value="${esc(i.public_id)}" ${selected.has(String(i.public_id))?'checked':''}></label>`).join('')}</div>`;}
 const isRecipes=mode==='recipes', selected=new Set((isRecipes?currentMoment.recipes:currentMoment.inspirations).map(x=>String(isRecipes?x.id:x.public_id))), items=isRecipes?sourceRecipes:sourceWallet;
 return `<div class="moment-section-search"><input id="moment-section-search" type="search" placeholder="${isRecipes?'Rezepte':'Inspirationen'} durchsuchen …"></div><div id="moment-section-picker" class="moment-section-picker">${items.map(i=>{const id=String(isRecipes?i.id:i.public_id);return `<label class="moment-section-picker-item"><span>${isRecipes?'':(i.source_image_url?`<img src="${esc(i.source_image_url)}" alt="" loading="lazy">`:'')}<span><strong>${esc(isRecipes?i.name:(i.title||'Inspiration'))}</strong><small>${esc(isRecipes?(i.calories?`${i.calories} kcal`:'Rezept'):(i.category||i.source_platform||'Inspiration'))}</small></span></span><input type="checkbox" value="${esc(id)}" ${selected.has(id)?'checked':''}></label>`}).join('')}</div>`;
}
async function openSectionEditor(mode){editMode=mode;document.querySelector('.moment-more')?.removeAttribute('open');if(mode==='recipes'||mode==='inspirations'||mode==='moments')await ensureSources();$('moment-section-editor-title').textContent=editorTitle(mode);$('moment-section-editor-body').innerHTML=editorMarkup(mode);bindSectionEditor();$('moment-section-editor').showModal();}
function bindSectionEditor(){const choice=$('moment-section-editor-body').querySelector('[data-choice]');choice?.querySelectorAll('button').forEach(b=>b.onclick=()=>{choice.querySelectorAll('button').forEach(x=>x.classList.toggle('is-selected',x===b));if(editMode==='timing')$('moment-section-date')?.classList.toggle('is-hidden',b.dataset.value!=='date');if(editMode==='audience'){if(b.dataset.value==='solo')$('moment-edit-people').value=1;if(b.dataset.value==='two')$('moment-edit-people').value=2;}});$('moment-section-search')?.addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase('de');$('moment-section-picker').querySelectorAll('.moment-section-picker-item').forEach(label=>label.hidden=!label.textContent.toLocaleLowerCase('de').includes(q));});}
function closeSectionEditor(){$('moment-section-editor')?.close();editMode=null;}
async function saveSectionEditor(){if(!editMode)return;const body={};if(editMode==='timing'){const selected=document.querySelector('[data-choice="timing"] .is-selected')?.dataset.value||'open';body.timing_code=selected;body.moment_date=selected==='date'?($('moment-edit-date').value||null):null;body.moment_time=selected==='date'?($('moment-edit-time').value||null):null;}else if(editMode==='audience'){body.audience_code=document.querySelector('[data-choice="audience"] .is-selected')?.dataset.value||'open';body.people_count=$('moment-edit-people').value||null;}else if(editMode==='notes'){body.notes=$('moment-edit-notes').value;}else if(editMode==='recipes'){body.recipe_ids=[...document.querySelectorAll('#moment-section-picker input:checked')].map(i=>Number(i.value));body.wallet_public_ids=(currentMoment.inspirations||[]).map(i=>i.public_id);}else if(editMode==='inspirations'){body.wallet_public_ids=[...document.querySelectorAll('#moment-section-picker input:checked')].map(i=>i.value);body.recipe_ids=(currentMoment.recipes||[]).map(r=>Number(r.id));}else if(editMode==='moments'){body.child_food_moment_public_ids=[...document.querySelectorAll('#moment-section-picker input:checked')].map(i=>i.value);}
 const btn=$('moment-section-save');btn.disabled=true;try{currentMoment=await api(`/food-moments/${encodeURIComponent(currentMoment.public_id)}`,{method:'PATCH',body:JSON.stringify(body)});closeSectionEditor();render(currentMoment);}catch(e){$('moment-section-feedback').textContent=e.message;}finally{btn.disabled=false;}}

async function addMomentToShoppingList(){if(!currentMoment)return;try{const result=await api(`/shopping-list/import/food-moment/${encodeURIComponent(currentMoment.public_id)}`,{method:'POST',body:JSON.stringify({})});const count=Number(result?.added)||0;const toast=document.getElementById('app-toast');if(toast){toast.textContent=`${count} Zutaten zur Einkaufsliste hinzugefügt.`;toast.classList.remove('is-hidden');toast.classList.add('is-visible');setTimeout(()=>{toast.classList.add('is-hidden');toast.classList.remove('is-visible');},2200);}else alert(`${count} Zutaten zur Einkaufsliste hinzugefügt.`);}catch(e){alert(e.message);}}

async function deleteMoment(){if(!currentMoment||!confirm(`„${currentMoment.title}“ wirklich löschen?`))return;try{await api(`/food-moments/${encodeURIComponent(currentMoment.public_id)}`,{method:'DELETE'});location.href='/foodMoments.html';}catch(e){alert(e.message);}}
function renderWorkspaceOptions(){const q=$('moment-workspace-search').value.trim().toLocaleLowerCase('de');$('moment-workspace-list').innerHTML=workspaceOptions.filter(w=>w.name.toLocaleLowerCase('de').includes(q)).map(w=>`<label class="recipe-workspace-option"><span class="recipe-workspace-option-main"><span class="recipe-workspace-option-icon">${icon('<rect x="4" y="4" width="16" height="16" rx="3"/>')}</span><span><strong>${esc(w.name)}</strong><small>${w.workspace_type==='personal'?'Persönlicher Workspace':'Workspace'}</small></span></span><input type="checkbox" class="recipe-workspace-checkbox" value="${esc(w.public_id)}" ${w.is_assigned?'checked':''}><span class="recipe-workspace-checkmark">✓</span></label>`).join('');}
function selectedWorkspaceIds(){return [...document.querySelectorAll('#moment-workspace-list .recipe-workspace-checkbox:checked')].map(i=>i.value);}
async function saveWorkspaceAssignments(){const ids=selectedWorkspaceIds();if(!ids.length){$('moment-workspace-save-state').textContent='Mindestens ein Workspace muss ausgewählt bleiben.';$('moment-workspace-save-state').classList.add('is-error');renderWorkspaceOptions();return;}try{$('moment-workspace-save-state').textContent='Speichert …';const result=await api(`/food-moments/${encodeURIComponent(currentMoment.public_id)}/workspace-assignments`,{method:'PUT',body:JSON.stringify({workspace_public_ids:ids})});workspaceOptions=result.workspaces||workspaceOptions;$('moment-workspace-save-state').textContent='Gespeichert';$('moment-workspace-save-state').classList.remove('is-error');if(result.current_workspace_still_assigned===false){const target=workspaceOptions.find(w=>w.is_assigned);if(target){await AuthShell.switchWorkspace(target.public_id);location.reload();}}else{currentMoment=await api(`/food-moments/${encodeURIComponent(currentMoment.public_id)}`);render(currentMoment);}}catch(e){$('moment-workspace-save-state').textContent=e.message;$('moment-workspace-save-state').classList.add('is-error');}}
async function openMomentWorkspaces(){document.querySelector('.moment-more')?.removeAttribute('open');try{const data=await api(`/food-moments/${encodeURIComponent(currentMoment.public_id)}/workspace-assignments`);workspaceOptions=data.workspaces||[];$('moment-workspace-search').value='';$('moment-workspace-save-state').textContent='';renderWorkspaceOptions();$('moment-workspace-overlay').classList.remove('is-hidden');$('moment-workspace-overlay').setAttribute('aria-hidden','false');}catch(e){alert(e.message);}}
function closeWorkspaces(){$('moment-workspace-overlay').classList.add('is-hidden');$('moment-workspace-overlay').setAttribute('aria-hidden','true');}
$('moment-workspace-close')?.addEventListener('click',closeWorkspaces);$('moment-workspace-done')?.addEventListener('click',closeWorkspaces);$('moment-workspace-search')?.addEventListener('input',renderWorkspaceOptions);$('moment-workspace-list')?.addEventListener('change',e=>{const c=e.target.closest('.recipe-workspace-checkbox');if(!c)return;const w=workspaceOptions.find(x=>x.public_id===c.value);if(w)w.is_assigned=c.checked;clearTimeout(saveTimer);saveTimer=setTimeout(saveWorkspaceAssignments,350);});$('moment-workspace-overlay')?.addEventListener('click',e=>{if(e.target===$('moment-workspace-overlay'))closeWorkspaces();});
$('moment-section-cancel')?.addEventListener('click',closeSectionEditor);$('moment-section-close')?.addEventListener('click',closeSectionEditor);$('moment-section-save')?.addEventListener('click',saveSectionEditor);$('moment-section-editor')?.addEventListener('close',()=>{$('moment-section-feedback').textContent='';});
document.addEventListener('auth:ready',loadMoment);if(window.AuthShell?.isReady?.())loadMoment();
