const momentState={timing:'open',audience:'open',contentType:'recipe',recipe:null,wallet:null,recipes:[],walletItems:[]};
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function api(path,options={}){const h=new Headers(options.headers||{});if(options.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await AuthShell.request(path,{...options,headers:h});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||'Aktion fehlgeschlagen.');return p;}
function setChoice(group,value){document.querySelectorAll(`#${group} button`).forEach(b=>b.classList.toggle('is-selected',b.dataset.value===value));}
function timingLabel(){return {now:'Jetzt',later_today:'Später heute',tomorrow:'Morgen',weekend:'Am Wochenende',date:$('moment-date').value?new Date($('moment-date').value+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}):'Bestimmter Tag',open:'Noch offen'}[momentState.timing]||'Noch offen';}
function audienceLabel(){return {solo:'Nur ich',two:'Zu zweit',family:'Familie',friends:'Freunde',guests:'Gäste',open:'Noch offen'}[momentState.audience]||'Noch offen';}
function contentLabel(){return momentState.recipe?.name||momentState.wallet?.title||'Noch offen';}
function suggestedTitle(){const when=timingLabel(), audience=audienceLabel(); if(momentState.timing==='open'&&momentState.audience==='open')return ''; if(momentState.audience==='open')return when; if(momentState.timing==='open')return audience; return `${when} · ${audience}`;}
function updatePreview(){const auto=suggestedTitle(); if(!$('moment-title').dataset.edited&&auto)$('moment-title').value=auto;$('preview-title').textContent=$('moment-title').value.trim()||'Noch ganz offen.';$('preview-when').textContent=timingLabel();$('preview-audience').textContent=audienceLabel();$('preview-content').textContent=contentLabel();}
function renderResults(){const q=$('moment-content-search').value.trim().toLocaleLowerCase('de');const box=$('moment-content-results');if(momentState.contentType==='open'){box.innerHTML='<div class="moment-open-state"><strong>Noch nichts festlegen.</strong><p>Völlig okay. Rezept, Inspiration und Einkauf können später dazukommen.</p></div>';return;} const items=momentState.contentType==='recipe'?momentState.recipes:momentState.walletItems;const filtered=items.filter(i=>String(i.name||i.title||'').toLocaleLowerCase('de').includes(q));if(!filtered.length){box.innerHTML='<p class="moment-picker-empty">Nichts gefunden.</p>';return;}box.innerHTML=filtered.map(i=>{const selected=momentState.contentType==='recipe'?momentState.recipe?.id===i.id:momentState.wallet?.public_id===i.public_id;return `<button type="button" class="moment-picker-item ${selected?'is-selected':''}" data-id="${esc(momentState.contentType==='recipe'?i.id:i.public_id)}"><span><strong>${esc(i.name||i.title||'Ohne Titel')}</strong><small>${esc(momentState.contentType==='recipe'?(i.portions?`${i.portions} Portionen`:'Rezept'):(i.category||i.source_platform||'Inspiration'))}</small></span><span>${selected?'✓':'+'}</span></button>`}).join('');box.querySelectorAll('.moment-picker-item').forEach(b=>b.onclick=()=>selectContent(b.dataset.id));}
function selectContent(id){if(momentState.contentType==='recipe'){momentState.recipe=momentState.recipes.find(i=>String(i.id)===String(id))||null;momentState.wallet=null;}else{momentState.wallet=momentState.walletItems.find(i=>i.public_id===id)||null;momentState.recipe=null;}renderResults();updatePreview();}
async function loadSources(){try{const [recipes,wallet]=await Promise.all([api('/recipes'),api('/wallet?status=saved')]);momentState.recipes=Array.isArray(recipes)?recipes:[];momentState.walletItems=Array.isArray(wallet)?wallet:[];const params=new URLSearchParams(location.search);const wid=params.get('wallet_id');if(wid){momentState.contentType='wallet';momentState.wallet=momentState.walletItems.find(i=>i.public_id===wid)||null;document.querySelectorAll('.moment-content-tabs button').forEach(b=>b.classList.toggle('is-active',b.dataset.content==='wallet'));}renderResults();updatePreview();}catch(e){$('moment-form-feedback').textContent=e.message;}}
document.querySelectorAll('#timing-choices button').forEach(b=>b.onclick=()=>{momentState.timing=b.dataset.value;setChoice('timing-choices',momentState.timing);$('moment-date-fields').classList.toggle('is-hidden',momentState.timing!=='date');updatePreview();});
document.querySelectorAll('#audience-choices button').forEach(b=>b.onclick=()=>{momentState.audience=b.dataset.value;setChoice('audience-choices',momentState.audience);if(momentState.audience==='solo')$('people-count').value=1;if(momentState.audience==='two')$('people-count').value=2;updatePreview();});
document.querySelectorAll('.moment-content-tabs button').forEach(b=>b.onclick=()=>{momentState.contentType=b.dataset.content;document.querySelectorAll('.moment-content-tabs button').forEach(x=>x.classList.toggle('is-active',x===b));$('moment-content-picker').classList.toggle('is-open-choice',momentState.contentType==='open');renderResults();updatePreview();});
$('moment-content-results').addEventListener('click',()=>{});$('moment-content-search').addEventListener('input',renderResults);$('moment-date').addEventListener('change',updatePreview);$('moment-time').addEventListener('change',updatePreview);$('moment-title').addEventListener('input',()=>{$('moment-title').dataset.edited='1';updatePreview();});
$('food-moment-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('create-food-moment-button');$('moment-form-feedback').textContent='';btn.disabled=true;try{const created=await api('/food-moments',{method:'POST',body:JSON.stringify({title:$('moment-title').value,timing_code:momentState.timing,moment_date:$('moment-date').value||null,moment_time:$('moment-time').value||null,audience_code:momentState.audience,people_count:$('people-count').value||null,recipe_id:momentState.recipe?.id||null,wallet_public_id:momentState.wallet?.public_id||null,notes:$('moment-notes').value})});location.href=`/foodMoment.html?id=${encodeURIComponent(created.public_id)}`;}catch(err){$('moment-form-feedback').textContent=err.message;}finally{btn.disabled=false;}});
document.addEventListener('auth:ready',loadSources); if(window.AuthShell?.isReady?.())loadSources();
