const list=document.getElementById('food-moments-list');
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));let allMoments=[];
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function momentDate(m){return m.moment_date||m.starts_at?.slice(0,10)||'';}
function dateValue(m){const value=momentDate(m);if(!value)return null;const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?null:d;}
function formatWhen(m){const d=dateValue(m);if(!d)return 'Noch offen';const today=new Date();today.setHours(0,0,0,0);const target=new Date(d);target.setHours(0,0,0,0);const diff=Math.round((target-today)/86400000);const time=m.moment_time||(!m.is_all_day&&m.starts_at?m.starts_at.slice(11,16):'');if(diff===0)return `Heute${time?` · ${time} Uhr`:''}`;if(diff===1)return `Morgen${time?` · ${time} Uhr`:''}`;if(diff===-1)return 'Gestern';return `${d.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:d.getFullYear()!==today.getFullYear()?'numeric':undefined})}${time?` · ${time} Uhr`:''}`;}
function richness(m){return (m.recipes?.length||0)+(m.inspirations?.length||0)+(m.notes?1:0)+(m.people_count?1:0);}
function detail(m){const parts=[];if(m.recipes?.length)parts.push(m.recipes.map(r=>r.name).join(', '));else if(m.inspirations?.length)parts.push(m.inspirations.map(i=>i.title).join(', '));if(m.people_count)parts.push(`${m.people_count} Personen`);return parts.join(' · ')||'Kann später weitergedacht werden.';}
function card(m,variant='normal'){const rich=richness(m)>=2;return `<article class="moment-overview-card ${rich?'is-rich':''} ${variant==='past'?'is-past':''}"><a class="moment-overview-main" href="/foodMoment.html?id=${encodeURIComponent(m.public_id)}"><span class="moment-overview-when">${esc(formatWhen(m))}</span><span class="moment-overview-copy"><strong>${esc(m.title)}</strong><small>${esc(detail(m))}</small></span><svg class="fc-icon" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></a>${variant==='past'?`<button class="moment-repeat-button" type="button" data-repeat-moment="${esc(m.public_id)}" data-title="${esc(m.title)}">Nochmal machen</button>`:''}</article>`;}
function section(title,kicker,items,kind,description=''){if(!items.length)return '';return `<section class="moment-overview-section ${kind}"><div class="moment-overview-heading"><div><p class="home-section-kicker">${esc(kicker)}</p><h2>${esc(title)}</h2>${description?`<p>${esc(description)}</p>`:''}</div><span>${items.length}</span></div><div class="moment-overview-grid">${items.map(m=>card(m,kind==='history'?'past':'normal')).join('')}</div></section>`;}
function render(){const q=(document.getElementById('moments-search')?.value||'').trim().toLocaleLowerCase('de');const today=todayKey();const filtered=allMoments.filter(m=>!q||`${m.title||''} ${(m.recipes||[]).map(r=>r.name).join(' ')} ${(m.inspirations||[]).map(i=>i.title).join(' ')} ${m.notes||''}`.toLocaleLowerCase('de').includes(q));
 const upcoming=filtered.filter(m=>momentDate(m)&&momentDate(m)>=today).sort((a,b)=>`${a.starts_at||momentDate(a)}`.localeCompare(`${b.starts_at||momentDate(b)}`));
 const open=filtered.filter(m=>!momentDate(m)).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));
 const past=filtered.filter(m=>momentDate(m)&&momentDate(m)<today).sort((a,b)=>`${b.starts_at||momentDate(b)}`.localeCompare(`${a.starts_at||momentDate(a)}`));
 const count=document.getElementById('moments-count');if(count)count.textContent=`${filtered.length} ${filtered.length===1?'Moment':'Momente'}`;
 if(!filtered.length){list.innerHTML=`<div class="moments-empty"><h2>${q?'Nichts gefunden.':'Noch kein Food Moment.'}</h2><p>${q?'Versuche einen anderen Suchbegriff.':'Der erste darf ganz klein anfangen.'}</p>${q?'':'<a href="/foodMomentCreate.html">Food Moment erstellen →</a>'}</div>`;return;}
 list.innerHTML=section('Was als Nächstes kommt','Bevorstehend',upcoming,'upcoming','Vom Alltag bis zum besonderen Anlass.')+section('Noch offen','Ohne Termin',open,'open','Gedanken und Vorhaben, die noch keinen festen Platz brauchen.')+section('Dein Food-Gedächtnis','Vergangen',past,'history','Vergangene Moments bleiben erhalten – und können wieder Ausgangspunkt für etwas Neues sein.');}
async function load(){try{const r=await AuthShell.request('/food-moments');const items=await r.json();if(!r.ok)throw new Error(items?.error||'Food Moments konnten nicht geladen werden.');allMoments=Array.isArray(items)?items:[];render();}catch(e){list.innerHTML=`<p>${esc(e.message)}</p>`;}}
async function repeatMoment(publicId,title){const button=document.querySelector(`[data-repeat-moment="${CSS.escape(publicId)}"]`);if(button)button.disabled=true;try{const r=await AuthShell.request(`/food-moments/${encodeURIComponent(publicId)}/repeat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});const data=await r.json();if(!r.ok)throw new Error(data?.error||'Food Moment konnte nicht wiederholt werden.');location.href=`/foodMoment.html?id=${encodeURIComponent(data.public_id)}`;}catch(e){alert(e.message);}finally{if(button)button.disabled=false;}}
function bindToggle(buttonId,panelId){document.getElementById(buttonId)?.addEventListener('click',()=>{const panel=document.getElementById(panelId);if(!panel)return;const open=!panel.classList.contains('is-hidden');panel.classList.toggle('is-hidden',open);document.getElementById(buttonId)?.classList.toggle('is-active',!open);if(!open)panel.querySelector('input')?.focus();});}
bindToggle('moments-search-toggle','moments-search-panel');document.getElementById('moments-search')?.addEventListener('input',render);document.addEventListener('click',e=>{const b=e.target.closest('[data-repeat-moment]');if(!b)return;e.preventDefault();repeatMoment(b.dataset.repeatMoment,b.dataset.title);});document.addEventListener('auth:ready',load);if(window.AuthShell?.isReady?.())load();
